
name: Simple Start Up
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build my virtual OS
    runs-on: Ubuntu-latest
    steps:
    - name: checkout my codes
      uses: actions/checkout@v2
    - name: Print and list out content
      run: |
        ls
        echo Hello There!
    - name: Checkout private repo
      uses: actions/checkout@v2
      with: 
        repository: Kuan-Zher/DevOps-Week-7-Practical
        token: ${{ secrets.Week7 }}
    - name: List contents
      run:  |
        ls
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with: 
        python-version: '3.10'
    - run: python my-script.py
    - name: install plugin
      run: |
        pip install pytest pytest-cov
        pytest --cov
